import { Character } from './Character.js'

export const characters = [
	// With one answer
	new Character("Mistral", []),
	new Character("Monsoon", []),
	new Character("Collei", []),
	new Character("Doraemon", []),
	new Character("Dori", []),
	new Character("Ganyu", []),
	new Character("Johnny-Bravo", []),
	new Character("Teppei", []),
	new Character("Tighnari", []),
	new Character("Venti", []),
	new Character("Yae-Miko", []),
	new Character("Yelan", []),
	new Character("Phineas", []),
	new Character("Ren", []),
	new Character("Yuzu", []),
	new Character("Satsuki", []),
	new Character("Natsume", []),
	new Character("Phineas", []),
	new Character("Jake", []),
	new Character("Finn", []),
	new Character("Sakura", []),
	new Character("Kiri", []),
	new Character("BMO", []),

	// With more answers
	new Character("Senko", ["Senko-San", "Senko san"]),
	new Character("Bart", ["Bart Simpson"]),
	new Character("Homer", ["Homer Simpson"]),
	new Character("Armstrong", ["Senator Armstrong", "Steven Armstrong"]),
	new Character("Peter-Griffin", ["Peter"]),
	new Character("Lois", ["Lois Griffin"]),
	new Character("Brian", ["Brian Griffin"]),
	new Character("Boris", ["Boris Popov", "Boris Vyacheslavovich Popov"]),
	new Character("Raiden", ["Jack", "Jack The Ripper"]),
	new Character("Chudd", ["Chudd Chudders"]),
	new Character("Jenny", ["Jennifer", "Jenny Wakeman", "Jennifer Wakeman"]),
	new Character("Kitty-Katswell", ["Kitty"]),
	new Character("Sandy-Cheeks", ["Sandy"]),
]